config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :attendances
  
  devise_for :admins
  
  root "events#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :created_events, class_name: 'Event', foreign_key: :admin_id
  has_many :attended_event, class_name: 'Attendance'
  # 1 admin = varios eventos
  # 1 admin = varias attendances
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    has_many :admin
    belongs_to :event

    # 1 attendance = 1 evento
    # 1 attendance = varios admins
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :location, presence: true
    validates :date, presence: true

    belongs_to :creator, class_name: 'Admin', foreign_key: :admin_id
    has_one :attendances, class_name: 'Attendance'

    # 1 evento = 1 admin criador
    # 1 evento = 1 attendance
end

app/models/user.rb
class User < ApplicationRecord    
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
  
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    def create
        # @attendance = current_admin.attendances.build(attendances_params)
        @attendance = Attendance.new(attendances_params)
        @attendance.admin_id = current_admin.id
        if @attendance.save
            redirect_to event_path(@attendance.event_id), notice: 'Attendance was successfully confirmed.'
        else
            render :show, status: :unprocessable_entity
        end
    end

    private
    def attendances_params
        params.require(:attendance).permit(:event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_admin!, only: [:new, :create, :edit]

    def index
        @events = Event.all
        @attendance = Attendance.new
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_admin.created_events.build(event_params)
        if @event.save
            redirect_to root_url
        else
            render 'new'
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])

        if @event.update(event_params)
            redirect_to @event
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def show
        @event = Event.find(params[:id])
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy

        redirect_to root_url
    end

    private
        def event_params
            params.require(:event).permit(:title, :description, :location, :date)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<%= form_with model: @event do |form|%>
    <div>
        <%= form.label "Title" %>
        <%= form.text_field :title %>
        
        <%= form.label "Description" %>
        <%= form.text_field :description %>

        <%= form.label "Location" %>
        <%= form.text_field :location %>
        
        <%= form.label "Date" %>
        <%= form.date_field :date %>

        <%= form.submit "Edit this event" %>
    </div>
    <%= button_to 'delete', event_path(@event), method: :delete, data: { confirm: "Are you sure" }, :class => "btn btn-danger btn-sm mt-2" %>
<% end %>

app/views/events/index.html.erb
<table class="table">
    <thead>
        <tr>
        <th scope="col"><%= "Title" %></th>
        <th scope="col"><%= "Description" %></th>
        <th scope="col"><%= "Location" %></th>
        <th scope="col"><%= "Date" %></th>
        </tr>
    </thead>
    <tbody>
        <% @events.each do |e| %>
        <tr>
            <td><%= link_to e.title, edit_event_path(e), :class => "link-dark" %></td>
            <td><%= e.description %></td>
            <td><%= e.location %></td>
            <td><%= e.date %></td>
            <td>
            <% if admin_signed_in? %>
                <%= form_with model: @attendance do |form|%>
                    <%= form.hidden_field :event_id, value: e.id %>

                    <%= form.submit "Participate" %>
                <% end %>
            <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>


<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<%= form_with model: @event do |form|%>
    <div>
        <%= form.label "Title" %>
        <%= form.text_field :title %>
        
        <%= form.label "Description" %>
        <%= form.text_field :description %>

        <%= form.label "Location" %>
        <%= form.text_field :location %>
        
        <%= form.label "Date" %>
        <%= form.date_field :date %>

        <%= form.submit "Create event" %>
    </div>
<% end %>

app/views/events/show.html.erb
<p>Title: <%= @event.title %></p>

<p>Location: <%= @event.location %></p>

<p>Description: <%= @event.description %></p>

<p>Date: <%= @event.date %><p>

<%= Attendance.where(event_id: @event.id).ids %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: 'shared/head'%>
  </head>

  <body>
    <%= render partial: 'shared/navbar'%>
    <%= yield%>
  </body>
</html>

app/views/shared/_head.html.erb
<title>Private Events</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Private events', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <% if admin_signed_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
          <%= link_to "Edit profile", edit_admin_registration_path, :class => 'nav-link d-inline p-2' %>
          <%= button_to "Logout", destroy_admin_session_path, method: :delete, :class => 'btn btn-primary d-inline p-2'%>
      <% else %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
          <span class="navbar-text">
            <%= link_to 'Login', new_admin_session_path, class: 'nav-link'%>
          </span>

          <span class="navbar-text">
            <%= link_to 'Sign Up', new_admin_registration_path, class: 'nav-link'%>
          </span>
      <% end %>
    </div>
  </div>
</nav>